import type { Metadata } from "next";
import { Slider } from "@/components/Slider/Slider";

export const metadata: Metadata = {
  title: "Slider App",
  description: "Generated by create next app",
};

export default async function Home() {
  return (
    <div className="relative h-full flex items-center justify-center overflow-x-hidden">
      <div className="container max-w-7xl w-full mx-auto h-full">
        <div className="h-full p-4 gap-6 flex flex-col justify-start lg:justify-center items-center">
          <Slider />
        </div>
      </div>
    </div>
  );
}
